package com.example.infs3634finalassignmentv3;

//The QuizBank class stores all the questions the Quiz will pull from

public class QuizBank {
    //All questions have a q_id that identifies them
    int q_id [] ={
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,

    };
    //The actual questions are stored as string in the questions array
    String questions[] ={
            "What is a Digital Firm?",
            "What are Key Corporate Assets?",
            "Define Information?",
            "What is Information Technology?",
            "What are the 3 activities of an Information System?",
            "What is a Business Model?",
            "What is data?",
            "What is Input?",
            "What is Processing?",
            "What is Output?",
            "What is Feedback?",
            "What is Strategy?",
            "What are Core Competencies?",
            "What is a Competitive Advantage?",
            "How are the barriers for market entry raised?",
            "What is an ERP system?",
            "Enterprise System Approach means?",
            "Define a Supply Chain:",
            "Define Supply Chain Management.",
            "Implementation must involve:",
            "Components of a CRM:",
            "Which phases does the Decision-Making Process include?",
            "Why are transactional databases not suitable for Business Analysis?",
            "Why is cyber security important?",
            "Motivations for cyber-attacks include:",
            "What is Malware?" ,
            "Identify the classic mistakes of Project management:",
            "Identify 5 moral dimensions of the information age?",
            "Define the Risk Aversion Principle.",
            "Define the Utilitarian Principle.",
            "Define Descartes' Rule of Change.",
            "Define the Golden Rule:",
            "Define Kant's Categorical Imperative",
            "If there is no Information System...",
            "What is an Incomplete representation?",
            "What is an Ambiguous Representation?",
            "What is a Meaningless State?",
            "What are the 6 Vs of Big Data?",
            "Information Systems helps organizational members make:",
            "What is the Business Model Canvas?"
    };

    //The answeres to the questions are store as strings in the answers array
    String answers[] ={
            "An organisation's significant business relationships with customer, suppliers and employees are digitally enabled and mediated",
            "Intellectual Property, core competencies, financial and human assets",
            "Data that has been shaped into a form that is meaningful and useful to human beings",
            "Consists of all the hardware and software that a firm needs to use in order to achieve its business objectives",
            "Input, Processing and Output",
            "Describes how a company produces, delivers and sells a product or service to create wealth",
            "Streams of raw facts representing events occurring in organisations or physical environment before they are organised and arranged into a form that people can understand",
            "Captures and collects raw data from within the organisation or from its external environment",
            "Converts the raw data input to a meaningful form",
            "Transfers the processed information to the people who will use it or to activities for which it will be used",
            "Output that is returned to appropriate members of an organisation to help them evaluate or correct the input stage",
            "Specific patterns of decision making to leverage on core competencies to attain competitive advantage",
            "Unique skills and proficiencies that can be utilized in value-creation activities. Core competencies are derived from specialized resources and coordination of abilities of management.",
            "Ability to excel better than your competitor in specific domains",
            "Invest in technology, High switching costs lock-in customers",
            "Manages daily operations and facilitates planning",
            "Consolidated information storage for different business activities",
            "Consists of all parties involved- directly or indirectly, in obtaining raw materials or a product",
            "The management of information flows between and among stages in a supply chain to maximise total supply chain efficiency, effectiveness and profitability",
            "People, Processes and Systems",
            "Customer Data, Sales, Marketing Analysis, Marketing, Customer Service",
            "Intelligence, Design, Choice, Implementation",
            "Contain only current, not historical data",
            "Because of the interconnectedness and social media",
            "Damage, Knowledge, Malicious intent, Financial Gain",
            "The detection of malware on the internet targeting the organisation or brand",
            "People, Process, Product, Technology",
            "Information Right and Obligations, Property right and Obligation, System Quality, Quality of Life, Accountability and Control",
            "Take the action that produces the least harm",
            "Take the action that produces the greatest good for all",
            "If an action is not right repeatedly then it is wrong to take it anytime",
            "Do unto others as you would have them do to you",
            "If an action is not right for everyone to take then it is not right for anyone",
            "there is no Business Intelligence",
            "Situation where one is not able to make certain decisions",
            "Situation where certain decisions that one makes are suboptimal",
            "Situation where certain decisions that one makes are wrong",
            "Volume, Variety, Velocity, Veracity, Variability, Value Proposition",
            "...Educated decisions in a systematic and optimal manner through proper data/information management",
            "Business Model Canvas is a strategic management and lean startup template for developing new or documenting existing business models"

    };
}

